apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-node-datasource
  labels:
    grafana_datasource: "1"
data:
  node-dashboard.json: |
    {
      "id": 1,
      "uid": "afaxsugr444jka",
      "orgId": 1,
      "name": "prometheus",
      "type": "prometheus",
      "typeLogoUrl": "public/plugins/prometheus/img/prometheus_logo.svg",
      "access": "proxy",
      "url": "http://test",
      "user": "",
      "database": "",
      "basicAuth": false,
      "basicAuthUser": "",
      "withCredentials": false,
      "isDefault": true,
      "jsonData": {
        "pdcInjected": false
      },
      "secureJsonFields": {},
      "version": 3,
      "readOnly": false,
      "apiVersion": ""
    }