apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-node-datasource
  labels:
    grafana_datasource: "1"
data:
  mimir-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.monitoring.svc:80/prometheus
        isDefault: true
        uid: bfb0va2ojn2m8b
        editable: true
        basicAuth: false
        withCredentials: false
        jsonData: {}
        secureJsonData: {}